import type { FgcLinia } from '../types/fgc';

// ⚠️ SEED DATA — curated subset of the real FGC network (lines with a direct
// connection to Barcelona: Barcelona–Vallès from Pl. Catalunya and
// Llobregat–Anoia from Pl. Espanya). Coordinates are real to ~4 decimals.
//
// In production this file is REGENERATED by `scripts/build-fgc-data.mjs` from
// the official GTFS (https://www.fgc.cat/google/google_transit.zip), which
// yields the complete stop set, exact shapes and official route colours. Until
// that runs against the live feed (dev hosts are outside the network
// allowlist), this seed keeps the whole feature functional and testable.

export interface FgcStaticStop {
  nom: string;
  lat: number;
  lng: number;
}

export const FGC_LINES: FgcLinia[] = [
  { id: 'fgc-L6', codi: 'L6', nom: 'Pl. Catalunya — Sarrià', origen: 'Pl. Catalunya', desti: 'Sarrià', color: '#7C4D9F', nomComplet: 'FGC L6' },
  { id: 'fgc-L7', codi: 'L7', nom: 'Pl. Catalunya — Av. Tibidabo', origen: 'Pl. Catalunya', desti: 'Av. Tibidabo', color: '#8C4A2F', nomComplet: 'FGC L7' },
  { id: 'fgc-L12', codi: 'L12', nom: 'Sarrià — Reina Elisenda', origen: 'Sarrià', desti: 'Reina Elisenda', color: '#B47EB3', nomComplet: 'FGC L12' },
  { id: 'fgc-S1', codi: 'S1', nom: 'Pl. Catalunya — Terrassa', origen: 'Pl. Catalunya', desti: 'Terrassa Nacions Unides', color: '#DD352B', nomComplet: 'FGC S1' },
  { id: 'fgc-S2', codi: 'S2', nom: 'Pl. Catalunya — Sabadell', origen: 'Pl. Catalunya', desti: 'Sabadell Parc del Nord', color: '#00A94F', nomComplet: 'FGC S2' },
  { id: 'fgc-S5', codi: 'S5', nom: 'Pl. Catalunya — Sant Cugat', origen: 'Pl. Catalunya', desti: 'Sant Cugat', color: '#7AC143', nomComplet: 'FGC S5' },
  { id: 'fgc-S6', codi: 'S6', nom: 'Pl. Catalunya — Universitat Autònoma', origen: 'Pl. Catalunya', desti: 'Universitat Autònoma', color: '#0089CF', nomComplet: 'FGC S6' },
  { id: 'fgc-S7', codi: 'S7', nom: 'Pl. Catalunya — Rubí', origen: 'Pl. Catalunya', desti: 'Rubí', color: '#F18A00', nomComplet: 'FGC S7' },
  { id: 'fgc-L8', codi: 'L8', nom: 'Pl. Espanya — Molí Nou', origen: 'Pl. Espanya', desti: 'Molí Nou-Ciutat Cooperativa', color: '#E6308A', nomComplet: 'FGC L8' },
  { id: 'fgc-S3', codi: 'S3', nom: 'Pl. Espanya — Can Ros', origen: 'Pl. Espanya', desti: 'Can Ros', color: '#9E6B3F', nomComplet: 'FGC S3' },
  { id: 'fgc-S4', codi: 'S4', nom: 'Pl. Espanya — Olesa de Montserrat', origen: 'Pl. Espanya', desti: 'Olesa de Montserrat', color: '#F4A81D', nomComplet: 'FGC S4' },
  { id: 'fgc-S8', codi: 'S8', nom: 'Pl. Espanya — Martorell', origen: 'Pl. Espanya', desti: 'Martorell-Enllaç', color: '#0072BB', nomComplet: 'FGC S8' },
  { id: 'fgc-R5', codi: 'R5', nom: 'Pl. Espanya — Manresa', origen: 'Pl. Espanya', desti: 'Manresa-Baixador', color: '#004A99', nomComplet: 'FGC R5' },
  { id: 'fgc-R6', codi: 'R6', nom: 'Pl. Espanya — Igualada', origen: 'Pl. Espanya', desti: 'Igualada', color: '#8E1F6B', nomComplet: 'FGC R6' },
];

// Stop catalogue (code → name + coordinates).
export const FGC_STOPS: Record<string, FgcStaticStop> = {
  // Barcelona–Vallès trunk + branches
  PC: { nom: 'Barcelona — Plaça Catalunya', lat: 41.3873, lng: 2.1699 },
  PR: { nom: 'Provença', lat: 41.3936, lng: 2.162 },
  GR: { nom: 'Gràcia', lat: 41.4015, lng: 2.1521 },
  SG: { nom: 'Sant Gervasi', lat: 41.403, lng: 2.1466 },
  MU: { nom: 'Muntaner', lat: 41.3989, lng: 2.1396 },
  BO: { nom: 'La Bonanova', lat: 41.4035, lng: 2.1356 },
  TT: { nom: 'Les Tres Torres', lat: 41.3996, lng: 2.1322 },
  SA: { nom: 'Sarrià', lat: 41.4006, lng: 2.1213 },
  RE: { nom: 'Reina Elisenda', lat: 41.3979, lng: 2.1139 },
  PD: { nom: 'Pàdua', lat: 41.409, lng: 2.1382 },
  PU: { nom: 'El Putxet', lat: 41.4118, lng: 2.143 },
  AT: { nom: 'Avinguda Tibidabo', lat: 41.4116, lng: 2.137 },
  PF: { nom: 'Peu del Funicular', lat: 41.4145, lng: 2.1102 },
  BV: { nom: 'Baixador de Vallvidrera', lat: 41.4179, lng: 2.1003 },
  LPL: { nom: 'Les Planes', lat: 41.4276, lng: 2.0905 },
  FL: { nom: 'La Floresta', lat: 41.45, lng: 2.084 },
  VD: { nom: 'Valldoreix', lat: 41.4665, lng: 2.0795 },
  SC: { nom: 'Sant Cugat', lat: 41.4736, lng: 2.0846 },
  UAB: { nom: 'Universitat Autònoma', lat: 41.5009, lng: 2.0936 },
  RU: { nom: 'Rubí', lat: 41.4915, lng: 2.0335 },
  SB: { nom: 'Sabadell Parc del Nord', lat: 41.5605, lng: 2.1042 },
  TE: { nom: 'Terrassa Nacions Unides', lat: 41.5683, lng: 2.0125 },
  // Llobregat–Anoia trunk
  ES: { nom: 'Barcelona — Plaça Espanya', lat: 41.3753, lng: 2.149 },
  MG: { nom: 'Magòria — La Campana', lat: 41.3666, lng: 2.1428 },
  IC: { nom: 'Ildefons Cerdà', lat: 41.3636, lng: 2.1378 },
  EU: { nom: 'Europa — Fira', lat: 41.3585, lng: 2.129 },
  CR: { nom: "L'Hospitalet — Av. Carrilet", lat: 41.3565, lng: 2.1098 },
  CO: { nom: 'Cornellà-Riera', lat: 41.3559, lng: 2.0708 },
  SBL: { nom: 'Sant Boi', lat: 41.3447, lng: 2.0386 },
  MN: { nom: 'Molí Nou — Ciutat Cooperativa', lat: 41.3527, lng: 2.0292 },
  ML: { nom: 'Martorell-Enllaç', lat: 41.4747, lng: 1.9303 },
  OL: { nom: 'Olesa de Montserrat', lat: 41.545, lng: 1.8865 },
  MR: { nom: 'Manresa-Baixador', lat: 41.7223, lng: 1.8307 },
  IG: { nom: 'Igualada', lat: 41.5793, lng: 1.6203 },
  CRO: { nom: 'Can Ros', lat: 41.3486, lng: 2.0235 },
};

// Ordered stop codes per line (defines list order + the stop-to-stop polyline).
export const FGC_LINE_STOPS: Record<string, string[]> = {
  L6: ['PC', 'PR', 'GR', 'SG', 'MU', 'BO', 'TT', 'SA', 'RE'],
  L7: ['PC', 'PR', 'GR', 'SG', 'PD', 'PU', 'AT'],
  L12: ['SA', 'RE'],
  S1: ['PC', 'PR', 'GR', 'SG', 'SA', 'PF', 'BV', 'LPL', 'FL', 'VD', 'SC', 'TE'],
  S2: ['PC', 'PR', 'GR', 'SG', 'SA', 'PF', 'BV', 'LPL', 'FL', 'VD', 'SC', 'SB'],
  S5: ['PC', 'PR', 'GR', 'SG', 'SA', 'PF', 'BV', 'LPL', 'FL', 'VD', 'SC'],
  S6: ['PC', 'PR', 'GR', 'SG', 'SA', 'PF', 'BV', 'LPL', 'FL', 'VD', 'SC', 'UAB'],
  S7: ['PC', 'PR', 'GR', 'SG', 'SA', 'PF', 'BV', 'LPL', 'FL', 'VD', 'SC', 'RU'],
  L8: ['ES', 'MG', 'IC', 'EU', 'CR', 'CO', 'SBL', 'MN'],
  S3: ['ES', 'MG', 'IC', 'EU', 'CR', 'CO', 'SBL', 'CRO'],
  S4: ['ES', 'MG', 'IC', 'EU', 'CR', 'CO', 'SBL', 'ML', 'OL'],
  S8: ['ES', 'MG', 'IC', 'EU', 'CR', 'CO', 'SBL', 'ML'],
  R5: ['ES', 'MG', 'IC', 'EU', 'CR', 'CO', 'SBL', 'ML', 'MR'],
  R6: ['ES', 'MG', 'IC', 'EU', 'CR', 'CO', 'SBL', 'ML', 'IG'],
};

// Maps the GTFS-RT route_id (numeric GTFS id) to our line code. Empty in the
// seed; the build pre-bake fills it so live vehicles match the selected line.
export const FGC_ROUTE_IDS: Record<string, string> = {};
