// trip_id → { c: line code, h: headsign }. Empty in the seed; regenerated by
// scripts/build-fgc-data.mjs from the GTFS trips.txt so the real-time feed
// (which omits route_id and headsign) can show each arrival/vehicle's line and
// destination. Kept in its own file so the (large) map only lands in the Pages
// Function bundle, not the frontend.
export const FGC_TRIPS: Record<string, { c: string; h: string }> = {};
